version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: uswds
    versions:
    - 2.10.0
    - 2.10.1
    - 2.10.2
    - 2.10.3
    - 2.11.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
